# Generated by Django 5.2.10 on 2026-03-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên người mua')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(default='Chờ xác nhận', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trái cây')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Danh mục')),
            ],
        ),
    ]
